Osmar
o…
En canal de voz

Aquí empieza el canal #tareas. 
g… — 01/06/2025 17:05
persistir colecciones en memoria en agregador (Gadi)
hacer una clase para el criterio (Fran)
coleccion to dto dentro de coleccion y dto to coleccion  (Osmar)
responsabilisa de la fuente de filtrar los hechos pasandole los criterios (Fran y Gadi)
4.1. cuando hace el get hechos pasar los criterios y filtra desde cada fuente
traigo todos los hechos y modulo para eliminar repetido a futuro implementar (Osmar)
que pasa cuando se esta ejecutando elcronjob y me solicitan hechos (Ivan)
6.1. decision: tenemos estas colecciones estan desactualizadas, se estan actualizando (ultima actualizaciona  tal hora) (Ivan)
fecha y hora de ultima actualizacion como atributo en coleccion (Osmar)
se esta instanciando un detector de spam por cada solicitud (Eitan)
8.1. patron de creacion para solicitud eliminacion (Eitan)
agregar adminmistrador para la fuente estatica en diagrama (Gadi)
 
g… — 11/06/2025 18:29
Tareas Entrega 3;
Modos de navegacion (Osmar, Gadi y Fran)
 
API administrativa de MetaMapa (Ivan)
API pública para otras instancias de MetaMapa (ver entrega anterior):(Eitan)
g… — 27/06/2025 18:14
Tareas del grupo modo navegacion
UNir concenso con curada
crear endpont para crear estrategia de concenso
hacer irrestricta
cronjob de etsrategias de concenso
Franco Ysrraelit — 10/07/2025 16:54
lindaaa
g… — 10/07/2025 17:06
Imagen
Imagen
g… — 10/07/2025 17:31
Imagen
g… — 16:34
Tipo de archivo adjunto: acrobat
correcciones G23, entrega 3 (1).pdf
603.53 KB
g… — 18:42
@startuml

class Hecho {
     -titulo: String
     -descripcion: String
     -autor: String
     -colecciones: Map<Coleccion, Boolean>
     -categoria: Categoria
     -fechaHecho: LocalDate
     -fechaCarga: LocalDate
     -ubicacion: Ubicacion
     -origenCarga: OrigenHecho
     -origenFuente: TipoFuente
     -multimedia: List<Multimedia>
     -esEditable: Boolean
     -esValido: boolean
}

class Coleccion {
    -titulo: String
    -descripcion: String
    -fuentes: List<Fuente>
    -categoria: String
    -handle: Handle
    -fechaInicio: LocalDate
    -fechaFin: LocalDate
    -criteriosDePertenencia: List<CriterioDePertenencia>
    -algoritmoConsenso: IAlgoritmoDeConsenso
    +navegarHechos(modoNavegacion: TipoModoNavegacion): List<Hecho>
    +filtrarHechos(filtros: List<CriterioDePertenencia>)
    +consensuarHechos():void
    +agregarFuente(fuente: Fuente): void
    +quitarFuente(fuente: Fuente): void
}

enum TipoModoNavegacion {
    IRRESTRICTA
    CURADA
}


interface IAlgoritmoDeConsenso {
    +consensuarhechos(hechos: List<Hecho>): List<Hecho>
}

class multiplesmenciones implements IAlgoritmoDeConsenso {
    +consensuarhechos(hechos: List<Hecho>): List<Hecho>
}

class mayoriaSimple implements IAlgoritmoDeConsenso {
    +consensuarhechos(hechos: List<Hecho>): List<Hecho>
}

class absoluta implements IAlgoritmoDeConsenso {
    +consensuarhechos(hechos: List<Hecho>): List<Hecho>
}








class Fuente{
    -webClient: WebClient
    +obtenerHechos(criterios: List<CriterioDePertenencia>)
}

class Importador{
    -pathArchivos: List<String>;
    -EstrategiaExtraccionHechos: EstrategiaExtraccionHechos
    +obtenerHechos(): map<String,Hecho>
    +csvExtractor(hechos, pathArchivos): FuenteEstatica
}


interface CriterioDePertenencia {
    +cumpleCriterio(hecho: Hecho): boolean
}


class CriterioPorFecha implements CriterioDePertenencia {
    -fechaInicio: LocalDate
    -fechaFin: LocalDate
    +cumpleCriterio(hecho: Hecho): boolean
}


class CriterioPorCategoria implements CriterioDePertenencia {
    -categoria: String
    +cumpleCriterio(hecho: Hecho): boolean
}


class CriterioPorUbicacion implements CriterioDePertenencia {
    -ubicacion: Ubicacion
    +cumpleCriterio(hecho: Hecho): boolean
}

... (134 líneas restantes)
Contraer
message.txt
5 KB
﻿
@startuml

class Hecho {
     -titulo: String
     -descripcion: String
     -autor: String
     -colecciones: Map<Coleccion, Boolean>
     -categoria: Categoria
     -fechaHecho: LocalDate
     -fechaCarga: LocalDate
     -ubicacion: Ubicacion
     -origenCarga: OrigenHecho
     -origenFuente: TipoFuente
     -multimedia: List<Multimedia>
     -esEditable: Boolean
     -esValido: boolean
}

class Coleccion {
    -titulo: String
    -descripcion: String
    -fuentes: List<Fuente>
    -categoria: String
    -handle: Handle
    -fechaInicio: LocalDate
    -fechaFin: LocalDate
    -criteriosDePertenencia: List<CriterioDePertenencia>
    -algoritmoConsenso: IAlgoritmoDeConsenso
    +navegarHechos(modoNavegacion: TipoModoNavegacion): List<Hecho>
    +filtrarHechos(filtros: List<CriterioDePertenencia>)
    +consensuarHechos():void
    +agregarFuente(fuente: Fuente): void
    +quitarFuente(fuente: Fuente): void
}

enum TipoModoNavegacion {
    IRRESTRICTA
    CURADA
}


interface IAlgoritmoDeConsenso {
    +consensuarhechos(hechos: List<Hecho>): List<Hecho>
}

class multiplesmenciones implements IAlgoritmoDeConsenso {
    +consensuarhechos(hechos: List<Hecho>): List<Hecho>
}

class mayoriaSimple implements IAlgoritmoDeConsenso {
    +consensuarhechos(hechos: List<Hecho>): List<Hecho>
}

class absoluta implements IAlgoritmoDeConsenso {
    +consensuarhechos(hechos: List<Hecho>): List<Hecho>
}








class Fuente{
    -webClient: WebClient
    +obtenerHechos(criterios: List<CriterioDePertenencia>)
}

class Importador{
    -pathArchivos: List<String>;
    -EstrategiaExtraccionHechos: EstrategiaExtraccionHechos
    +obtenerHechos(): map<String,Hecho>
    +csvExtractor(hechos, pathArchivos): FuenteEstatica
}


interface CriterioDePertenencia {
    +cumpleCriterio(hecho: Hecho): boolean
}


class CriterioPorFecha implements CriterioDePertenencia {
    -fechaInicio: LocalDate
    -fechaFin: LocalDate
    +cumpleCriterio(hecho: Hecho): boolean
}


class CriterioPorCategoria implements CriterioDePertenencia {
    -categoria: String
    +cumpleCriterio(hecho: Hecho): boolean
}


class CriterioPorUbicacion implements CriterioDePertenencia {
    -ubicacion: Ubicacion
    +cumpleCriterio(hecho: Hecho): boolean
}


 class Ubicacion {
   -latitud: Double
   -longitud: Double
 }


class SolicitudEliminacion{
    -solicitante: Contribuyente
    -hecho: Hecho
    -justificacion: String
    -estado: EstadoSolicitudEliminacion
    -historialDeEstados: List<EstadoSolicitudEliminacion>
    +cambiarEstadoHecho(administrador, estado): void
    -cambiarEstadoSolicitud(estado): void
    -actualizarHistorial():void
    +validarJustificacion(justificacion): string
}

class EstadoSolicitudEliminacion{
    -evaluador: Administrador
    -tiempoDeRespuesta: Integer
    -fechaDeCreacion: LocalDateTime
    -fechaDeEvaluacion: LocalDateTime
    -estado: PosibleEstadoSolicitudEliminacion
}

enum PosibleEstadoSolicitudEliminacion {
      PENDIENTE
      ACEPTADA
      RECHAZADA
}

class Handle{
-value: String
+equals()
+hashCode()
+toString(): String
}




class Categoria{
-nombre: String
}

class Ubicacion{
-latitud: Double
-longitud: Double
}



class Multimedia{
    -urlImagen: string
}


enum OrigenHecho {
    CARGA_MANUAL
    DATASET
    CONTRIBUYENTE
}

enum TipoFuente{
PROXY,
DINAMICA,
ESTATICA
}





interface EstrategiaExtraccionHechos{
    +obtenerHechosDesde(pathArchivo): map<String,Hecho>
}


class EstrategiaExtraccionHechosCSV implements EstrategiaExtraccionHechos{
    +obtenerHechosDesde(pathArchivo): map<String,Hecho>
}


class Contribuyente{
   -nombre: String
   -apellido: String
   -fechaDeNacimiento: LocalDate
   +obtenerEdad(): Integer
}

class Administrador{
    -nombre: String
   -apellido: String
   -fechaDeNacimiento: LocalDate
}

interface IDetectorSpam{
+detectarSpam(justificacion: String)
}

class DetectorSpam implements IDetectorSpam{
+detectarSpam(justificacion: String)
}







    Hecho --> Categoria
    Hecho --> Ubicacion
    Hecho -->"*" Multimedia
    Hecho --> OrigenHecho
    Hecho --> TipoFuente
    Hecho --> "*"Coleccion

  Coleccion --> Fuente
  Coleccion -->"*" CriterioDePertenencia
  SolicitudEliminacion --> Hecho
  SolicitudEliminacion --> Contribuyente
   Importador --> EstrategiaExtraccionHechos
  SolicitudEliminacion --> "*"EstadoSolicitudEliminacion
    EstadoSolicitudEliminacion --> PosibleEstadoSolicitudEliminacion
    EstadoSolicitudEliminacion --> Administrador
    Coleccion --> Handle
    Coleccion --> IAlgoritmoDeConsenso




@enduml
message.txt
5 KB