@startuml

class Hecho {
     -titulo: String
     -descripcion: String
     -autor: String
     -colecciones: Map<Coleccion, Boolean>
     -categoria: Categoria
     -fechaHecho: LocalDate
     -fechaCarga: LocalDate
     -ubicacion: Ubicacion
     -origenCarga: OrigenHecho
     -origenFuente: TipoFuente
     -multimedia: List<Multimedia>
     -esEditable: Boolean
     -esValido: boolean
}

class Coleccion {
    -titulo: String
    -descripcion: String
    -fuentes: List<Fuente>
    -categoria: String
    -handle: Handle
    -fechaInicio: LocalDate
    -fechaFin: LocalDate
    -criteriosDePertenencia: List<CriterioDePertenencia>
    -algoritmoConsenso: IAlgoritmoDeConsenso
    +navegarHechos(modoNavegacion: TipoModoNavegacion): List<Hecho>
    +filtrarHechos(filtros: List<CriterioDePertenencia>)
    +consensuarHechos():void
    +agregarFuente(fuente: Fuente): void
    +quitarFuente(fuente: Fuente): void
}

enum TipoModoNavegacion {
    IRRESTRICTA
    CURADA
}


interface IAlgoritmoDeConsenso {
    +consensuarhechos(hechos: List<Hecho>): List<Hecho>
}

class Multiplesmenciones implements IAlgoritmoDeConsenso {
    +consensuarhechos(hechos: List<Hecho>): List<Hecho>
}

class MayoriaSimple implements IAlgoritmoDeConsenso {
    +consensuarhechos(hechos: List<Hecho>): List<Hecho>
}

class Absoluta implements IAlgoritmoDeConsenso {
    +consensuarhechos(hechos: List<Hecho>): List<Hecho>
}

class Fuente{
    -webClient: WebClient
    +obtenerHechos(criterios: List<CriterioDePertenencia>)
}

class Importador{
    -pathArchivos: List<String>;
    -estrategiasPorExtension: Map<String, EstrategiaExtraccionHecho>
    +obtenerHechos(): List<Hecho>
    +procesarArchivo(pathArchivo, extension): List<Hecho>
}


interface CriterioDePertenencia {
    +cumpleCriterio(hecho: Hecho): boolean
}


class CriterioPorFecha implements CriterioDePertenencia {
    -fechaInicio: LocalDate
    -fechaFin: LocalDate
    +cumpleCriterio(hecho: Hecho): boolean
}


class CriterioPorCategoria implements CriterioDePertenencia {
    -categoria: String
    +cumpleCriterio(hecho: Hecho): boolean
}


class CriterioPorUbicacion implements CriterioDePertenencia {
    -ubicacion: Ubicacion
    +cumpleCriterio(hecho: Hecho): boolean
}


 class Ubicacion {
    -latitud: Double
    -longitud: Double
}


class SolicitudEliminacion{
    -solicitante: Contribuyente
    -hecho: Hecho
    -justificacion: String
    -estados: List<EstadoSolicitud>
    +cambiarEstadoSolicitud(estado): void
    +validarJustificacion(justificacion): string
}

class EstadoSolicitud{
    -evaluador: Administrador
    -fechaDeCreacion: LocalDateTime
    -fechaDeEvaluacion: LocalDateTime
    -estado: PosibleEstadoSolicitud
    +calcularTiempoDeRespuesta(fechaDeCreacion,fechaDeEvaluacion): Long
}

enum PosibleEstadoSolicitud {
      PENDIENTE
      ACEPTADA
      RECHAZADA
}

class Handle{
    -value: String
    +equals()
    +hashCode()
    +toString(): String
}


class Categoria{
    -nombre: String
}

class Multimedia{
    -urlImagen: string
}


enum OrigenHecho {
    CARGA_MANUAL
    DATASET
    CONTRIBUYENTE
}

enum TipoFuente{
    PROXY
    DINAMICA
    ESTATICA
}

interface EstrategiaExtraccionHechos{
    +obtenerHechosDesde(pathArchivo): List<Hecho>
}

class EstrategiaExtraccionHechosCSV implements EstrategiaExtraccionHechos{
    +obtenerHechosDesde(pathArchivo): List<Hecho>
}

class Contribuyente{
   -nombre: String
   -apellido: String
   -fechaDeNacimiento: LocalDate
   +obtenerEdad(): Integer
}

class Administrador{
   -nombre: String
   -apellido: String
   -fechaDeNacimiento: LocalDate
}

interface IDetectorSpam{
    +isSpam(justificacion: String)
}

class DetectorSpam implements IDetectorSpam{
    +isSpam(justificacion: String)
}






    Hecho --> Categoria
    Hecho --> Ubicacion
    Hecho -->"*" Multimedia
    Hecho --> OrigenHecho
    Hecho --> TipoFuente
    Hecho --> "*"Coleccion

    Coleccion --> TipoModoNavegacion
    Coleccion --> Fuente
    Coleccion -->"*" CriterioDePertenencia
    SolicitudEliminacion --> Hecho
    SolicitudEliminacion --> Contribuyente
    Importador --> EstrategiaExtraccionHechos
    SolicitudEliminacion --> "*"EstadoSolicitud
    EstadoSolicitud --> PosibleEstadoSolicitud
    EstadoSolicitud --> Administrador
    Coleccion --> Handle
    Coleccion --> IAlgoritmoDeConsenso




@enduml