@startuml
class Coleccion {

titulo: String
descripcion: String
fuente: FuenteEstatica
hechos: map<String,Hecho>
categoria: String
fechaInicio: LocalDate
fechaFin: LocalDate
cargarHechos(): void+ filtrarHechos(filtro): List<Hecho>
}





 class Ubicacion {
   -latitud: Double
   -longitud: Double
 }

  class SolicitudEliminacion{
    -solicitante: Contribuyente

justificacion: String
estado: EstadoSolicitudEliminacion
hecho: Hecho
+ cambiarEstadoHecho(): void
}



   enum EstadoSolicitudEliminacion {
       PENDIENTE
       ACEPTADA
       RECHAZADA
     }

 class Hecho {

titulo: String
descripcion: String
autor: String
categoria: String-ubicacion: Ubicacion
fechaHecho: LocalDate
fechaCarga: LocalDate
origen: OrigenHecho
multimedia: Multimedia
esValido: boolean


    }

  class Multimedia{
    -urlImagen: string
  }



  enum OrigenHecho {
    CARGA_MANUAL
    DATASET
    CONTRIBUYENTE
  }


  class FuenteEstatica{

pathArchivos: List<String>;
    EstrategiaExtraccionHechos: EstrategiaExtraccionHechos
    +obtenerHechos(): map<String,Hecho>
    +cambiarEstrategia(estrategiaExtraccionHechos): FuenteEstatica
}

  interface EstrategiaExtraccionHechos{
    + extraerHechos(fuente): map<String,Hecho>
  }

    class EstrategiaExtraccionHechosCSV implements EstrategiaExtraccionHechos{
        + extraerHechos(fuente): map<String,Hecho>
    }



class Contribuyente{

nombre: String
apellido: String
fechaDeNacimiento: LocalDate

+obtenerEdad(): Integer
}






  Coleccion --> FuenteEstatica
  Coleccion --> Hecho
  OrigenHecho <-- Hecho
  Ubicacion <--* Hecho
  SolicitudEliminacion --> Hecho
  SolicitudEliminacion --> Contribuyente
   FuenteEstatica --> EstrategiaExtraccionHechos
  SolicitudEliminacion --> EstadoSolicitudEliminacion

  Multimedia <--* Hecho
@enduml