@startuml MetaMapa_Entrega1


class Coleccion {
   - titulo: String
   - descripcion: String
   - fuente: FuenteEstatica
   - hechos: map<String,Hecho>
   - criterioPertenencia: CriterioPertenencia
   - cargarHechos(): void
 }

 class CriterioPertenencia {
   - nombre: String
   - lugar: Lugar
   - fechaInicnio: LocalDateTime
   - fechaFin: LocalDateTime
   + cumpleConCriterio(Hecho): boolean
 }



 class Ubicacion {
   -latitud: Double
   -longitud: Double
 }

  class SolicitudEliminacion{
    -solicitante: Contribuyente
    - justificacion: String
    - estado: EstadoSolicitudEliminacion
    - hecho: Hecho
    + cambiarEstadoHecho(): void
  }

  class Solicitudes{
  - solicitudes: List<SolicitudEliminacion>
    + cargarSolicitud(solicitudEliminacion): void
  }

   enum EstadoSolicitudEliminacion {
       PENDIENTE
       ACEPTADA
       RECHAZADA
     }

 class Hecho {
   - titulo: String
   - descripcion: String
   - categoria: String
   -ubicacion: Ubicacion
   - fechaHecho: LocalDate
   - fechaCarga: LocalDate
   - origen: OrigenHecho
   - multimedia: Multimedia
   - esValido: boolean

   + solicitarEliminacion(justificacion): void
    }

  class Multimedia{
    -urlImagen: string

  }

  interface Usuario{
     + subirHecho(nombre): void
     + visualizarHechos(): List<Hecho>
     + visualizarColecciones(filtro): List<Coleccion>
  }

  enum OrigenHecho {
    CARGA_MANUAL
    DATASET
    CONTRIBUYENTE
  }


  class FuenteEstatica{
    - archivosCSV: List<String>
    - normalizarTexto(texto): String
    + obtenerHechos(): map<String,Hecho>
  }



class Contribuyente implements Usuario{
    - nombre: String
    - apellido: String
    - edad: Integer
   + solicitarEliminacion(solicitud): void
}


  class Administrador implements Usuario{
    - idAdmin: Integer
    + crearColeccion(fuente, criterioPertenencia): void
    + importarHechos(fuente): map<String,Hechos>
    +aceptarSolicitudEliminacion(solicitudEliminacion): void
  }

  Coleccion --> FuenteEstatica
  Coleccion -->"*" Hecho
  OrigenHecho *--> Hecho
  Ubicacion *--> Hecho
  Administrador --> Coleccion
  Administrador --> SolicitudEliminacion
  SolicitudEliminacion --> Hecho
  SolicitudEliminacion --> Contribuyente
  Solicitudes -->"*" SolicitudEliminacion
  SolicitudEliminacion --> EstadoSolicitudEliminacion
  Coleccion *--> CriterioPertenencia
  Multimedia *--> Hecho







@enduml
